# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://172.18.0.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "172.18.0.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k3s-1"
    ipAddress: "172.18.0.201"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "90:e2:ba:78:39:e8"
        dhcp: false
        addresses:
          - "172.18.0.201/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.18.0.254"
        mtu: 1500
        vip:
          ip: "172.18.0.200"
  - hostname: "k3s-2"
    ipAddress: "172.18.0.15"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "0c:c4:7a:1e:ac:4c"
        dhcp: false
        addresses:
          - "172.18.0.15/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "172.18.0.254"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

