apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:JUx6pUy3QXD9ibleCvcUaHaGKA7DvNnUwtIlGUtdN3Uvx/fHtlE/PSMGjAJPLVE499ZhlaWwGLyNbvKbCuBcQZkEv03OeVvRYHo=,iv:qU/UdfIa5VGCEPytsphu1vbS9VneypSdncpkACbY9BY=,tag:/FGT7k66P96HYVbI3jF5BA==,type:str]
sops:
  age:
    - recipient: age1d0lg405jmump3r0dua63s32487hu26ydy86jqtdht7lcsmtn3uusm3e36k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQyszRWNvMFp4ZjhlbHJ4
        cEFzd3JHaGJkVWRBL2QyMkNycjgzUzF0MkcwCmZFOTVQbDZWZzFsZXljK0hyTHFK
        R2dicGNZeUVKUHUwUjZxczN0YThuQ1UKLS0tIENmZnFwVjhQemJsOHZPNEg2QUNZ
        WExFaXNwUUhpeG1samFkQ2Nlb2RSWVUK21LOIFRYrJcVjNllUa+Qpi8+CgJVnguG
        iOeMj9LoiCW8p73R3XA5qFfB/Yh0Vo/uHywi2fiD4REhrXcnY1c81Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-25T08:10:09Z"
  mac: ENC[AES256_GCM,data:Wr6pN1pt+gxAR9N4M2BAf6SYjqYs87pGA95VCicNK16V3BtlN66iYnOSyFiSEODZJEGR8ptAr6t9mvNFAhp0V8zC0rE5BcZpzW+wIWECtXMeKpemw3sFfxHS7JJbi461qNzgbbLLXebIIjQYZ/anPYTKeZEwRC2WRdZ1Ep8+sko=,iv:YsYWQOZkZyvvrW+/mPHybCxZqj9AJxSVfXmOW1lJdwU=,tag:/Rh9MBD3+6knIMHhROWgXg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
